# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.7'
#    - name: Test with Maven
#      run: mvn -B test --file pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven Wrapper chmod
      run: chmod u+x ./mvnw
    - name: Build with Maven Wrapper
      run: ./mvnw package

    - uses: actions/upload-artifact@v2
      with:
        name: skillcatchupsep
        path: target/skillcatchupsep-0.0.1-SNAPSHOT.jar

#  deploy:
    - name: make keyfile
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: echo "$SECRET_KEY" > keyfile && chmod 600 keyfile

    - name: stop at EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: ssh -o 'StrictHostKeyChecking no' ${EC2_USER}@${EC2_HOST} -i keyfile "./stop.bash"
      timeout-minutes: 1

    - name: sleep 29
      run: sleep 29

    - name: scp artifact to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: scp -o 'StrictHostKeyChecking no' -i keyfile target/skillcatchupsep-0.0.1-SNAPSHOT.jar "$EC2_USER"@"$EC2_HOST":~/app
      timeout-minutes: 1

    - name: sleep 31
      run: sleep 31

    - name: start at EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: ssh -o 'StrictHostKeyChecking no' ${EC2_USER}@${EC2_HOST} -i keyfile "./start.bash"
      timeout-minutes: 1
